In [8]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import roc_auc_score, precision_score, recall_score, roc_curve, accuracy_score

from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV

data = pd.read_csv('german.csv', sep=';')

#X = data.iloc[:, 1:].to_numpy()
"""
XX = data[
    [
    'Account_Balance', 
    'Duration_of_Credit_monthly',
    'Payment_Status_of_Previous_Credit',
    'Length_of_current_employment', 
    'Most_valuable_available_asset',
    ]
]
X = XX.to_numpy()
#"""
XX = data[
    [
    'Account_Balance', #
    'Duration_of_Credit_monthly', #
    'Payment_Status_of_Previous_Credit', #
    #'Purpose',
    #'Credit_Amount',
    #'Value_Savings_Stocks',
    'Length_of_current_employment', #
    #'Instalment_per_cent',
    'Sex_Marital_Status', #
    'Guarantors', #
    #'Duration_in_Current_address',
    'Most_valuable_available_asset', #
    #'Age_years',
    #'Concurrent_Credits',
    #'Type_of_apartment',
    'No_of_Credits_at_this_Bank', #
    #'Occupation',
    #'No_of_dependents',
    #'Telephone',
    #'Foreign_Worker'
    ]
] 
X = XX.to_numpy()
y = data.iloc[:, 0].to_numpy()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
data.head()

,Creditability,Account_Balance,Duration_of_Credit_monthly,Payment_Status_of_Previous_Credit,Purpose,Credit_Amount,Value_Savings_Stocks,Length_of_current_employment,Instalment_per_cent,Sex_Marital_Status,...,Duration_in_Current_address,Most_valuable_available_asset,Age_years,Concurrent_Credits,Type_of_apartment,No_of_Credits_at_this_Bank,Occupation,No_of_dependents,Telephone,Foreign_Worker
0,1,1,18,4,2,1049,1,2,4,2,...,4,2,21,3,1,1,3,1,1,1
1,1,1,9,4,0,2799,1,3,2,3,...,2,1,36,3,1,2,3,2,1,1
2,1,2,12,2,9,841,2,4,2,2,...,4,1,23,3,1,1,2,1,1,1
3,1,1,12,4,0,2122,1,3,3,3,...,2,1,39,3,1,2,2,2,1,2
4,1,1,12,4,0,2171,1,3,4,3,...,4,2,38,1,2,2,2,1,1,2

In [9]:


# Определение модели
mlp_model = MLPClassifier(random_state=42, max_iter=500)

# Задание сетки параметров для поиска
param_grid = {
    'hidden_layer_sizes': [(30,), (60,),(130,),(140,),(150,),(160,),(170,),(180,)],
    #'max_iter': [200, 300, 400, 500],
}

# Создание экземпляра GridSearchCV
grid_search = GridSearchCV(mlp_model, param_grid, cv=5, scoring='roc_auc')

# Обучение модели
grid_search.fit(X_train, y_train)

# Лучшие гиперпараметры
best_params = grid_search.best_params_

# Прогноз на тестовых данных с лучшей моделью
mlp_pred = grid_search.predict_proba(X_test)[:,1]

# Расчет метрик для MLP нейронной сети
mlp_roc_auc = roc_auc_score(y_test, mlp_pred)

print("\nMLP (Neural Network) метрики:")
print(f"Лучшие гиперпараметры: {best_params}")
print(f"ROC AUC: {mlp_roc_auc:.5f}")

c:\Users\poedatel lavashey\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(

MLP (Neural Network) метрики:
Лучшие гиперпараметры: {'hidden_layer_sizes': (60,)}
ROC AUC: 0.82544